services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics status"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:13
    container_name: auth-db
    ports:
      - "${AUTH_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-db:
    image: postgres:13
    container_name: user-db
    ports:
      - "${USER_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${USER_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "4001:4001"
    depends_on:
      auth-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  user-service:
    build:
      context: ./user-service
    env_file:
      - ./user-service/.env
    ports:
      - "4002:4002"
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  gateway-service:
    build:
      context: ../gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      AUTH_SERVICE_URL: http://auth-service:4001
      USER_SERVICE_URL: http://user-service:4002
      FRONTEND_ORIGIN: http://localhost:5173
    depends_on:
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  auth-db-data:
  user-db-data: